version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: lockfile-only
    directory: /
    schedule:
      interval: daily
    labels:
      - auto-approve
      - automerge
      - dependencies
      - security
    # Disable version updates for npm dependencies, only use Dependabot for security updates
    open-pull-requests-limit: 0
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - auto-approve
      - automerge
      - dependencies
    groups:
      github-actions-breaking:
        update-types:
          - major
      github-actions-backward-compatible:
        update-types:
          - minor
          - patch
