name: "Add LICENSE file to Go Repositories"

on:
  workflow_dispatch: {}

jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - id: set-matrix
        run: |
          provider=$(jq -rcM "{ provider: keys }" provider.json)
          echo "matrix=$provider" >> $GITHUB_OUTPUT

  add-license-file:
    needs: build-provider-matrix
    name: "Add LICENSE File"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 10
    steps:
      - name: Checkout this repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: main

      - name: Checkout cdktf-provider-${{ matrix.provider }}-go Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: cdktf/cdktf-provider-${{ matrix.provider }}-go
          token: ${{ secrets.GH_COMMENT_TOKEN }}
          path: provider

      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@867a1a2a064a0626db322392806428f7dc59cb3e # v1.1.2

      - name: Set git identity
        run: |-
          git config user.name "team-tf-cdk"
          git config user.email "github-team-tf-cdk@hashicorp.com"
        working-directory: ./provider

      - name: Delete old branches from previous runs
        run: |
          git branch -r | egrep -o "add-update-license-file.*"  | xargs -n 1 git push --delete origin
        working-directory: ./provider

      - name: Add Mozilla Public License
        run: copywrite license --spdx "MPL-2.0"
        working-directory: ./provider
        env:
          GH_REPO: cdktf/cdktf-provider-${{ matrix.provider }}-go
          GITHUB_TOKEN: ${{ secrets.GH_COMMENT_TOKEN }}

      - name: Check for changes
        id: git_diff
        run: |
          if (( $(git status -s | wc -l) > 0 )); then echo "has_changes=true" >> $GITHUB_OUTPUT; fi
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: Sleep for 2 seconds to avoid rate limits
        run: sleep 2s

      - if: steps.git_diff.outputs.has_changes
        name: Commit license file and push changes
        run: |
          git checkout -b add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}
          git add .
          git commit -m "Add / Update LICENSE file"
          git push --set-upstream origin add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: "Create PR"
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GH_COMMENT_TOKEN }}
          retries: 5
          retry-exempt-status-codes: 400,401,404
          script: |
            const {resolve} = require('path')
            const scriptPath = resolve("./main/.github/lib/create-pr")
            const script = require(scriptPath)
            await script({
              github,
              branchName: "add-update-license-file-${{ github.run_number }}-${{ github.run_attempt }}",
              prTitle: "Add / Update LICENSE file",
              fullRepoName: "cdktf-provider-${{matrix.provider}}-go",
              mergePullRequest: true
            })
