name: "Add Codeowners file to Go Repositories"

on:
  workflow_dispatch: {}

jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          # TODO: TESTING ONLY
          # provider=$(jq -rcM "{ provider: keys }" provider.json)
          provider='{"provider":["hashicups"]}'
          echo "matrix=$provider" >> $GITHUB_OUTPUT

  add-codeowners-file:
    needs: build-provider-matrix
    name: "Add Codeowners File"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 10
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout cdktf-provider-${{ matrix.provider }}-go Repository
        uses: actions/checkout@v2
        with:
          repository: cdktf/cdktf-provider-${{ matrix.provider }}-go
          token: ${{ secrets.GH_COMMENT_TOKEN }}
          path: provider

      - uses: actions/github-script@v4
        name: Copy codeowners file to provider repo
        with:
          script: |
            const {resolve} = require('path')
            const scriptPath = resolve("./main/.github/lib/copy-codeowners-file")
            const script = require(scriptPath)
            script()

      - name: Check for changes
        id: git_diff
        run: |
          if (( $(git status -s | wc -l) > 0 )); then echo "has_changes=true" >> $GITHUB_OUTPUT; fi
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: Commit codeowners file and push changes
        run: |
          git checkout -b add-update-codeowners-file-${{ github.run_number }}-${{ github.run_attempt }}
          git add .
          git commit -m "Add / Update CODEOWNERS file"
          git push --set-upstream origin add-update-codeowners-file-${{ github.run_number }}-${{ github.run_attempt }}
        working-directory: ./provider

      - if: steps.git_diff.outputs.has_changes
        name: "Create PR"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_COMMENT_TOKEN }}
          script: |
            const {resolve} = require('path')
            const scriptPath = resolve("./main/.github/lib/create-pr")
            const script = require(scriptPath)
            await script({
              github,
              branchName: "add-update-codeowners-file-${{ github.run_number }}-${{ github.run_attempt }}",
              prTitle: "Add / Update CODEOWNERS file",
              fullRepoName: "cdktf-provider-${{matrix.provider}}-go"
            })
