name: automerge
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - ready_for_review
      - reopened
      - synchronize
concurrency: ${{ github.workflow }}-${{ github.head_ref }}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && !contains(github.event.pull_request.labels.*.name, 'do-not-merge') && github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Turn on automerge for this PR by a trusted user or bot
        if: github.event.pull_request.user.login == 'team-tf-cdk' || contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.pull_request.author_association) || github.actor == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.GH_COMMENT_TOKEN }}
        run: gh pr merge --auto --squash ${{ github.event.pull_request.number }}
