name: "Create Next PR"

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: set-matrix
        run: |
          provider=$(jq -rcM "{ provider: keys }" provider.json)
          echo "matrix=$provider" >> $GITHUB_OUTPUT

  create-next-pr:
    needs: build-provider-matrix
    name: "Create Next PR"
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 10
    steps:
      - name: Trigger workflow
        run: gh workflow run next-cdktf-version-pr -R cdktf/cdktf-provider-${{ matrix.provider }}
        env:
          GH_TOKEN: ${{ secrets.GH_COMMENT_TOKEN }}
