name: "Deploy CDKTF Stack"

on:
  workflow_call:
    inputs:
      stacks:
        required: true
        description: JSON-stringified list of stacks to deploy, e.g. # [{ "stack": "my-stack" }]
        type: string
      upgrade-repositories:
        required: true
        type: boolean

jobs:
  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(inputs.stacks)}}
      max-parallel: 10

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36
        with:
          terraform_version: 1.7.0
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_wrapper: false

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Deploy
        run: "$(yarn bin)/cdktf deploy --auto-approve '${{ matrix.stack }}'"
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
          CDKTF_LOG_LEVEL: all

      - name: Send failures to Slack
        if: ${{ failure() && !cancelled() }}
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          payload: |
            {
              "provider_name": "stack deploy ${{ matrix.stack }}",
              "run_url": "https://github.com/cdktf/cdktf-repository-manager/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.FAILURE_SLACK_WEBHOOK_URL }}

  upgrade:
    if: inputs.upgrade-repositories
    needs:
      - terraform
    uses: ./.github/workflows/upgrade-repositories.yml
    secrets: inherit
