name: "Diff CDKTF Stack"

on:
  workflow_call:
    inputs:
      stacks:
        required: true
        description: JSON-stringified list of stacks to deploy, e.g. # [{ "stack": "my-stack" }]
        type: string

jobs:
  terraform:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(inputs.stacks)}}
      max-parallel: 10

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.6.4
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}
          terraform_wrapper: false

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "18"

      - run: yarn install
      - name: Synth
        run: "$(yarn bin)/cdktf synth"
      - name: Plan
        id: plan
        run: |
          set -o pipefail
          cd cdktf.out/stacks/${{ matrix.stack }}
          rm -rf .terraform 
          terraform init 
          terraform plan -no-color | tee ../../../plan_stdout_${{ matrix.stack }}.txt; echo $?
          set +o pipefail
        continue-on-error: true
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GH_COMMENT_TOKEN }}
          script: |
            const {resolve} = require('path')
            const scriptPath = resolve("./.github/lib/comment-plan-output")
            require(scriptPath)({
              context, 
              github,
              planOutcome: "${{steps.plan.outcome}}",
              pusher: "${{github.actor}}",
              actionName: "${{github.event_name}}",
              workingDirectory: "${{env.tf_actions_working_dir}}",
              workflowName: "${{github.workflow}}",
              stackName: "${{matrix.stack}}" 
            })
