name: GitHub Actions Version Updater

on:
  schedule:
    # Every monday at 13:37 UTC
    - cron: 37 13 * * 1
  workflow_dispatch: {}

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
  PR_TITLE: "chore(deps): update github workflow actions"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
      - name: Find and close older versions of this same PR
        run: |
          prlist=$(gh search prs --repo ${{ github.repository }} --state open --match title "$PR_TITLE" --json number --jq '.[].number')
          [ -n "$prlist" ] && gh pr close -d --comment "Closing this because I'm about to open a newer PR." ${prlist}
        continue-on-error: true
      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@a7fd643bb3e9c1ef8f5c70bb5b645f5a2a9f395c # TSCCR: no entry for repository "saadmk11/github-actions-version-updater"
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
          committer_username: "team-tf-cdk"
          committer_email: "github-team-tf-cdk@hashicorp.com"
          commit_message: ${{ env.PR_TITLE }}
          pull_request_title: ${{ env.PR_TITLE }}
          pull_request_team_reviewers: "@cdktf/tf-cdk-team"
          pull_request_labels: "dependencies,automated"
          update_version_with: "release-commit-sha"

  pin:
    runs-on: ubuntu-latest
    needs: [update]
    steps:
      - name: Find and checkout the PR just created
        id: find_pr
        run: |
          prnumber=$(gh search prs --repo ${{ github.repository }} --state open --match title "$PR_TITLE" --json number --jq '.[].number')
          echo "pr=$prnumber" >> $GITHUB_OUTPUT
          gh pr checkout ${prnumber}
      - name: Setup TSCCR helper
        uses: hashicorp/setup-tsccr@v1
      - name: Pin all workflows based on TSCCR
        run: tsccr-helper -pin-all-workflows .
      - name: Set git identity
        run: |-
          git config user.name "hashicorp-tsccr[bot]"
          git config user.email "hashicorp-tsccr[bot]@users.noreply.github.com"
      - name: Check if there are any changes
        id: get_changes
        run: echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.get_changes.outputs.changed != 0
        run: |-
          git add .
          git commit -s -m "chore(deps): pin all workflows based on HashiCorp TSCCR"
          git push
      - name: Add automerge label
        run: |
          gh pr edit ${{ steps.find_pr.outputs.pr }} --add-label "automerge"
