name: upgrade-actions
on:
  schedule:
    - cron: 37 1 * * 1
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  pin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup TSCCR helper
        uses: hashicorp/setup-tsccr-helper@v1
        with:
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
      - name: Pin all workflows based on TSCCR
        run: tsccr-helper gha update -latest .
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        with:
          branch: auto/upgrade-actions
          base: main
          commit-message: "chore(deps): pin trusted workflows based on HashiCorp TSCCR"
          title: "chore(deps): pin trusted workflows based on HashiCorp TSCCR"
          body: "This PR upgrades all GitHub Actions to newer versions so long as they have been verified by HashiCorp's security team."
          labels: dependencies,automated,automerge
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
          author: hashicorp-tsccr[bot] <hashicorp-tsccr[bot]@users.noreply.github.com>
          committer: hashicorp-tsccr[bot] <hashicorp-tsccr[bot]@users.noreply.github.com>
          signoff: true
          delete-branch: true
