name: "upgrade-main in all provider repos"
on:
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-provider-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: set-matrix
        run: |
          provider=$(jq -rcM "{ provider: keys }" provider.json)
          echo "matrix=$provider" >> $GITHUB_OUTPUT
  upgrade-main:
    needs: build-provider-matrix
    name: "Trigger upgrade-main"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-provider-matrix.outputs.matrix)}}
      max-parallel: 1
    steps:
      - name: Trigger the upgrade-main workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GH_COMMENT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: "cdktf",
                repo: "cdktf-provider-${{ matrix.provider }}",
                workflow_id: "upgrade-main.yml",
                ref: "main"
            })
      - name: Delay running the next step to avoid API rate limit issues
        run: sleep 10s
        shell: bash
