name: upgrade-terraform
on:
  schedule:
    - cron: 32 23 * * 0
  workflow_dispatch: {}
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  upgrade:
    name: Upgrade Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install
        run: yarn install
      - name: Get latest Terraform version
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |-
            const script = require('./scripts/check-terraform-version.js')
            await script({github, context, core})
      - name: Parse latest Terraform version into variables
        id: latest_version
        run: |-
          TERRAFORM_VERSION_MINOR=$(cut -d "." -f 2 <<< "$NEW_TERRAFORM_VERSION")
          echo "NEW_TERRAFORM_VERSION_MINOR=$TERRAFORM_VERSION_MINOR" >> $GITHUB_ENV
          echo "value=$NEW_TERRAFORM_VERSION" >> $GITHUB_OUTPUT
          echo "minor=$TERRAFORM_VERSION_MINOR" >> $GITHUB_OUTPUT
      - name: Update the Terraform version used in GitHub Actions workflows
        run: |-
          find ./.github/workflows -type f -name "*.yml" ! -path "./.github/workflows/upgrade-terraform.yml" -print0 | xargs -0 sed -i "s/terraform_version: .*/terraform_version: $NEW_TERRAFORM_VERSION/g"
      - name: Create pull request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6.0.0
        with:
          base: main
          branch: auto/upgrade-terraform-1-${{ steps.latest_version.outputs.minor }}
          commit-message: "chore: upgrade Terraform to ${{ steps.latest_version.outputs.value }}"
          title: "chore: upgrade Terraform to ${{ steps.latest_version.outputs.value }}"
          body: |-
            This PR initiates the upgrade of the version of Terraform used by this project's `diff` and `deploy` workflows to version `${{ steps.latest_version.outputs.value }}`.
            Unfortunately, not everything can be automated, and the following steps need to be completed manually:
             
            - Update the _Terraform Version_ in the TFC web UI in the following workspaces:
              - [ ] [custom-constructs](https://app.terraform.io/app/cdktf-team/workspaces/custom-constructs/settings/general)
              - [ ] [prebuilt-providers](https://app.terraform.io/app/cdktf-team/workspaces/prebuilt-providers/settings/general)
              - [ ] [prebuilt-providers-official-new](https://app.terraform.io/app/cdktf-team/workspaces/prebuilt-providers-official-new/settings/general)
              - [ ] [prebuilt-providers-partners](https://app.terraform.io/app/cdktf-team/workspaces/prebuilt-providers-partners/settings/general)
            - Rerun the checks and carefully inspect the diff output before merging this PR.
          labels: automated,dependencies
          token: ${{ secrets.GH_TOKEN_ACTIONS_UPDATER }}
          author: team-tf-cdk <github-team-tf-cdk@hashicorp.com>
          committer: team-tf-cdk <github-team-tf-cdk@hashicorp.com>
          signoff: true
          delete-branch: true
